apiVersion: v1
kind: Pod
metadata:
  name: nginxtest
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: ebstest
  containers:
    - name: nginxtest
      image: nginx:latest
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage