apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mikesnginxapps.simplyengineering.com
spec:
  group: simplyengineering.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced
  names:
    kind: MikesNginxApp
    plural: mikesnginxapps
    singular: mikesnginxapp
    shortNames:
    - mna