apiVersion: constraints.gatekeeper.sh/v1beta1
kind: blockprivcontainers
metadata:
  name: blockprivcontainers
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    annotation: "priv-containers"