---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - simplyanengineer.com.simplyanengineer.com
  resources:
  - mikesapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - simplyanengineer.com.simplyanengineer.com
  resources:
  - mikesapis/finalizers
  verbs:
  - update
- apiGroups:
  - simplyanengineer.com.simplyanengineer.com
  resources:
  - mikesapis/status
  verbs:
  - get
  - patch
  - update
