kubectl create -f - <<EOF
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-testing
spec:
  acme:
    # Staging Server From LetsEncrypt
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: asoftware417@gmail.com
    privateKeySecretRef:
      name: letsencrypt-testing
    solvers:
      - http01:
          ingress:
            class: nginx
EOF