apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: thenjdevopsguy/gowebappskaffold
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
manifests:
  rawYaml:
  - goapp.yaml
